repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black
        alias: python
        files: ^backend/
        args: ["--line-length=120"]
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: isort (python)
        alias: python
        files: ^backend/
        args: ["--profile", "black", "-l 120"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        alias: python
        files: ^backend/
        args: [ "--max-complexity=12", "--max-line-length=120" ]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v10.0.2
    hooks:
      - id: eslint
        name: eslint-frontend
        entry: npm run --prefix ./frontend lint
        files: \.[jt]sx?$
        types: [file]
        language: node
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: prettier-frontend
        entry: npm run --prefix ./frontend format
        language: node
        files: ^frontend/
        pass_filenames: false

exclude: 'backend/alembic/.*'
