"""optional people name

Revision ID: 6887e35b75af
Revises: b0ff8316b979
Create Date: 2026-01-31 23:05:50.486175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6887e35b75af'
down_revision: Union[str, Sequence[str], None] = 'b0ff8316b979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'primary_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'primary_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
