"""consolidate roles and character

Revision ID: 69b38973ed34
Revises: 907985688276
Create Date: 2026-02-01 16:06:31.481786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69b38973ed34'
down_revision: Union[str, Sequence[str], None] = '907985688276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('title_directors')
    op.drop_table('title_writers')
    op.alter_column('title_principals', 'characters',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               postgresql_using=(
                   "CASE "
                   "WHEN characters IS NULL OR btrim(characters) = '' OR characters = '\\\\N' THEN NULL "
                   "WHEN left(ltrim(characters), 1) = '[' THEN "
                   "string_to_array(replace(trim(BOTH '[]' FROM characters), '\"', ''), ',') "
                   "ELSE ARRAY[characters] "
                   "END"
               ))
    op.create_index(op.f('ix_title_principals_category'), 'title_principals', ['category'], unique=False)
    op.create_index(op.f('ix_title_principals_nconst'), 'title_principals', ['nconst'], unique=False)
    op.create_index(op.f('ix_title_principals_tconst'), 'title_principals', ['tconst'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_title_principals_tconst'), table_name='title_principals')
    op.drop_index(op.f('ix_title_principals_nconst'), table_name='title_principals')
    op.drop_index(op.f('ix_title_principals_category'), table_name='title_principals')
    op.alter_column('title_principals', 'characters',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using="array_to_string(characters, ',')")
    op.create_table('title_writers',
    sa.Column('tconst', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nconst', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['nconst'], ['people.nconst'], name=op.f('title_writers_nconst_fkey')),
    sa.ForeignKeyConstraint(['tconst'], ['titles.tconst'], name=op.f('title_writers_tconst_fkey')),
    sa.PrimaryKeyConstraint('tconst', 'nconst', name=op.f('title_writers_pkey'))
    )
    op.create_table('title_directors',
    sa.Column('tconst', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nconst', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['nconst'], ['people.nconst'], name=op.f('title_directors_nconst_fkey')),
    sa.ForeignKeyConstraint(['tconst'], ['titles.tconst'], name=op.f('title_directors_tconst_fkey')),
    sa.PrimaryKeyConstraint('tconst', 'nconst', name=op.f('title_directors_pkey'))
    )
    # ### end Alembic commands ###
