"""index title aka

Revision ID: 907985688276
Revises: 9ab50865ce22
Create Date: 2026-02-01 15:18:34.198920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907985688276'
down_revision: Union[str, Sequence[str], None] = '9ab50865ce22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_title_akas_title_id'), 'title_akas', ['title_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_title_akas_title_id'), table_name='title_akas')
    # ### end Alembic commands ###
