"""optional rating one2one

Revision ID: 9ab50865ce22
Revises: feadbef3fabc
Create Date: 2026-02-01 13:04:32.677471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab50865ce22'
down_revision: Union[str, Sequence[str], None] = 'feadbef3fabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_episodes_parent_tconst'), 'episodes', ['parent_tconst'], unique=False)
    op.create_index(op.f('ix_episodes_tconst'), 'episodes', ['tconst'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodes_tconst'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_parent_tconst'), table_name='episodes')
    # ### end Alembic commands ###
