"""initial imdb schema

Revision ID: b0ff8316b979
Revises: 
Create Date: 2026-01-31 15:58:53.684317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0ff8316b979'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('nconst', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('death_year', sa.Integer(), nullable=True),
    sa.Column('primary_professions', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('known_for_titles', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.PrimaryKeyConstraint('nconst')
    )
    op.create_table('titles',
    sa.Column('tconst', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_adult', sa.Boolean(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.PrimaryKeyConstraint('tconst')
    )
    op.create_table('episodes',
    sa.Column('tconst', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_tconst', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_tconst'], ['titles.tconst'], ),
    sa.ForeignKeyConstraint(['tconst'], ['titles.tconst'], ),
    sa.PrimaryKeyConstraint('tconst')
    )
    op.create_table('title_akas',
    sa.Column('title_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('types', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('attributes', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('is_original', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.tconst'], ),
    sa.PrimaryKeyConstraint('title_id', 'ordering')
    )
    op.create_table('title_directors',
    sa.Column('tconst', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nconst', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['nconst'], ['people.nconst'], ),
    sa.ForeignKeyConstraint(['tconst'], ['titles.tconst'], ),
    sa.PrimaryKeyConstraint('tconst', 'nconst')
    )
    op.create_table('title_principals',
    sa.Column('tconst', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('nconst', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('characters', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['nconst'], ['people.nconst'], ),
    sa.ForeignKeyConstraint(['tconst'], ['titles.tconst'], ),
    sa.PrimaryKeyConstraint('tconst', 'ordering')
    )
    op.create_table('title_ratings',
    sa.Column('tconst', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('num_votes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tconst'], ['titles.tconst'], ),
    sa.PrimaryKeyConstraint('tconst')
    )
    op.create_table('title_writers',
    sa.Column('tconst', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nconst', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['nconst'], ['people.nconst'], ),
    sa.ForeignKeyConstraint(['tconst'], ['titles.tconst'], ),
    sa.PrimaryKeyConstraint('tconst', 'nconst')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('title_writers')
    op.drop_table('title_ratings')
    op.drop_table('title_principals')
    op.drop_table('title_directors')
    op.drop_table('title_akas')
    op.drop_table('episodes')
    op.drop_table('titles')
    op.drop_table('people')
    # ### end Alembic commands ###
