"""add ImportTask model

Revision ID: b241453a2ae7
Revises: 69b38973ed34
Create Date: 2026-02-11 22:16:10.938113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b241453a2ae7'
down_revision: Union[str, Sequence[str], None] = '69b38973ed34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_compressed', sa.Integer(), nullable=False),
    sa.Column('size_raw', sa.Integer(), nullable=False),
    sa.Column('import_start_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_tasks')
    # ### end Alembic commands ###
