"""optional rating one2one

Revision ID: feadbef3fabc
Revises: 6887e35b75af
Create Date: 2026-02-01 11:48:00.846614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feadbef3fabc'
down_revision: Union[str, Sequence[str], None] = '6887e35b75af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_title_ratings_tconst'), 'title_ratings', ['tconst'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_title_ratings_tconst'), table_name='title_ratings')
    # ### end Alembic commands ###
